# 2-11

    const calulator ={
    plus: function(a,b)
    return a + b;  == 5
    }

    const plusresult=calulator.plus(2,3);

여기서 plusresult는 5가 된다

이게 가능한 이유는 return을 했기 떄문에 가능한 일이다.

## 한번 return 을하면 function은 끝난다.

한번 return 을 하면

function을 하면 그 코드는 작동하지 않는다는 의믿이기 떄문이다.

_return 밑에있는것은 실행되지 않는다_

## console.log를 하고 싶지 않는 이유

그 이유는 function 외부에서 values를 제공받기 위해서
ss
